services:
  - type: web
    name: tursicol
    env: node
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        sync: false
